name: СОРАС
description: Торговый дом Сорас
contacts:
  - link: 'tel:+74912252695'
    name: +7 4912 25 26 95
    icon: phone
    description: телефон

  - link: 'tel:+79109012525'
    name: +7 910 901 25 25
    icon: phone
    description: телефон

  - link: 'kontakty.html'
    name: 'Контакты'
    icon: map
    description: карта

  - link: 'https://t.me/tdsoras'
    name: 'телеграм'
    icon: telegram
    description: 

  - link: ''
    name: 'с 9:00-17:00'
    icon: time
    description:  ''

  - link: '#price'
    name: 'Прайс'
    icon: time
    description:  ''

blocks:    
  - name: Теплоизоляция
    shade : red
    link: '#'

  - name: Кровельные материалы
    shade : gray

  - name:  Гидроизоляция
    shade : red
    link: '#'



theme: null
sass:
  sass_dir: _sass
  style: compressed
collections:
  pages:
    permalink: '/:collection/:title'
  slideshow:
    output: false
plugins_dir:
  - jekyll-sass-converter
defaults:
  - values:
      layout: page
