name:VIVA 
description: Academy Hair VIVA
contacts:

  - link: 'tel:+74912282344'
    name: +7 (4912) 28-23-44
    icon: phone
    description: телефон

  - link: 'kontakty.html'
    name: 'Контакты'
    icon: map
    description: карта

  - link: 't.me/academyviva'
    name: 'телеграм'
    icon: telegram
    description: 

  - link: 't.me/academyvivachat'
    name: 'телеграм'
    icon: telegram
    description: 

  - link: 'https://vk.com/vivahairs'
    name: 'контакт'
    icon: telegram
    description: 

  - link: ''
    name: 'с 9:00-21:00'
    icon: time
    description:  ''

  - link: 'https://disk.yandex.ru/d/wxQEzO3HXj6-LA'
    name: 'Скачать прайс'
    icon: 
    description:  ''




theme: null
sass:
  sass_dir: _sass
  style: compressed
collections:
  pages:
    permalink: '/:collection/:title'
  slideshow:
    output: false
plugins_dir:
  - jekyll-sass-converter
defaults:
  - values:
      layout: page
